### ISSUE TITLE
Add proposal type to delegate DAO's XTZs

### ISSUE THREAD

**Issue by pasqu4le** [tezos-commons/baseDAO#306]
# Clarification and motivation

We'vw been asked for the ability for both `registryDAO` and `treasuryDAO` to delegate the DAO XTZs to a baker.

In order to do this we'll need to use the [`SET_DELEGATE`](https://tezos.gitlab.io/michelson-reference/#instr-SET_DELEGATE) instructions and add a new proposal type that will allow updating (setting or removing) a delegate for the DAO.

# Acceptance criteria

Both `registryDAO` and `treasuryDAO` have a proposal type that uses `SET_DELEGATE` to update the DAO's delegate

**Comment by csoreff** [comment]
In relation to this, would also be helpful to have a default entrypoint that allows the treasury to receive a regular XTZ transfer without calling the separate entrypoint, otherwise reward distribution would result in an error.  Would also allow people to easily donate to a DAO.

**Comment by sras** [comment]
@csoreff We already have a number of entrypoints that can accept regular XTZ transfer as part of the call. 

But from your description, it seems that you want to include a `default` entrypoint with a unit argument, to the main contract parameter (so not just treasury variant), so that the contract can be called without specifying any argument at all. 

Is this correct?

**Comment by csoreff** [comment]
@sras 

It was my understanding that:

- The balance of the contract is the balance of the treasury
- The contract cannot accept regular XTZ transfers, such as a payout for staking rewards
- A transaction will fail if I try to send XTZ to the contract address, without calling a specific entrypoint.

If the above is true, yes it would be great if that was possible via a `default` entrypoint without specifying arguments.  Thanks!

**Comment by sras** [comment]
@csoreff 

Sorry for the delay in replying. But after some discussion, we have some doubts regarding what you mean by "treasury" here 

> The balance of the contract is the balance of the treasury

If by "balance of treasury", you mean the amount of XTZ that the contract controls, that is, the amount returned by a call like  `tezos-client get balance for <contract>`, then we are in agreement.

If it is not what you meant, please clarify.

>The contract cannot accept regular XTZ transfers, such as a payout for staking rewards

The contract has entrypoints that can accept XTZ transfers as part of the call, but I am not sure if they can be used to pay staking reward. Because it requires invoking an entrypoint that triggers some contract action, in addition to accepting the transfered funds.

> A transaction will fail if I try to send XTZ to the contract address, without calling a specific entrypoint.

Well, to be exact, you can call the contract with the full parameter, and that does not require specifying an entrypoint (even though an entrypoint might be implied by the parameter value). So for example if the full parameter was `or (unit %ep1) (unit %ep2)`, then calling the full contract with `Left Unit` will work even without specifying the entrypoint (but it ll be the same as calling it with entrypoint `ep1` and value `Unit`, so we can consider this calling `ep1` implicitly). 

So while you can call the contract without specifying an entrypoint, by passing the full parameter,  as I said earlier, I think it would not be practical to use this for the purpose of transfering XTZ funds to the contract. Because right now all the branches of the parameter results in some contract action, and many of the parameter branches even rject XTZ fund transfer if included with the call.

**Comment by csoreff** [comment]
Ideally we want to be able to send XTZ to the DAO without requiring any custom tx structuring. For example, any non-technical person just sending XTZ as usual via Kukai wallet/etc, or a baker just using their scripts to pay out rewards to every delegator. A regular user or baker is not going to take the time to customize parameters, so it depends if it's the default behavior or not.

**Comment by sras** [comment]
@csoreff Got it. We will add a `default` entrypoint with a `unit` parameter that can accept XTZ transfers. This should allow transfers to the contract without specifiying an entrypoint or a parameter in the call.
