### ISSUE TITLE
Allow the option of unlimited number of proposals in a cycle

### ISSUE THREAD

**Issue by obstropolos** [tezos-commons/baseDAO#68]
### Clarification and motivation

Straightforward - enable an unlimited number of proposals in a cycle as an option for DAOs created using this framework.

**Comment by gromakovsky** [comment]
This limit is a safety measure. We store all proposals in a strict `set` because we need a way to iterate over proposals starting from the oldest ones (in `flush`). We can't use `big_map`s for this purpose because it's impossible to iterate over them or at least pick the smallest element. Since this set is strict, each item added to it increases the cost of all operations (because it's part of the storage and the whole storage must be read). If we unlimit the number of proposals, an attacker can submit proposals until they hit gas limit and thus cause more expensive operations to always fail. It can potentially stale the contract.

This attack can be expensive to execute because every proposal requires its create to freeze a certain amount of tokens, but it really depends on DAO configuration, in some DAOs it can be not too expensive. Since this attack is theoretically possible, I think that any security audit will likely highlight it as vulnerability, so it's better to avoid it.

**Comment by gromakovsky** [comment]
Btw, currently the limit is set to 500, but I guess this value is quite arbitrary. If we keep the limit, I think we should check how gas consumption depends on the number of proposals in the storage, update the default limit accordingly and, ideally, have a test where we add maximal number of proposals and assert that gas consumption is within certain limits.

So I think we should either remove the limit (easiest option) or keep it, but make it based on experiments, not just a random value.

**Comment by obstropolos** [comment]
Makes sense to us - 500 limit should be fine at the moment, it covers most edge cases at this point.

**Comment by pasqu4le** [comment]
Since #316 has been closed this issue is resolved (number of proposal is no longer limited) and previous effort to test limits are no longer necessary.
